package review

import (
	"fmt"
	"strings"
)

const aiCommentLead = "**AI-generated review comment** — tool: **appr-ai-sal**, agent: **%s**\n\n"

// trimSuggestionBlock drops leading and trailing blank (whitespace-only) lines
// but preserves every content line verbatim, including its leading
// indentation. GitHub applies a ```suggestion block as the literal replacement
// for the anchored line(s), so stripping leading whitespace (as TrimSpace
// would) silently breaks indentation-sensitive files like YAML or Python: the
// reviewer clicks "Apply suggestion" and gets a left-shifted, malformed line.
func trimSuggestionBlock(s string) string {
	lines := strings.Split(s, "\n")
	start := 0
	for start < len(lines) && strings.TrimSpace(lines[start]) == "" {
		start++
	}
	end := len(lines)
	for end > start && strings.TrimSpace(lines[end-1]) == "" {
		end--
	}
	return strings.Join(lines[start:end], "\n")
}

// ReviewCommentBody formats the GitHub comment body for a finding (same as ToReview).
func ReviewCommentBody(specialist string, f Finding) string {
	body := fmt.Sprintf(aiCommentLead, specialist) + f.Comment
	if SuggestionPostsToGitHub(f) {
		if f.SuggestionSynthesized {
			body += "\n\n_Suggestion derived from the comment by appr-ai-sal — review before applying._"
		} else if f.SuggestionRepaired {
			body += "\n\n_Suggestion generated by appr-ai-sal's suggestion-repair pass — review before applying._"
		}
		s := trimSuggestionBlock(f.Suggestion)
		body += "\n\n```suggestion\n" + s + "\n```"
	}
	return body
}

// ReviewCommentBodyForFileLevel formats the GitHub comment body for a
// finding being posted at the file level (subject_type=file) instead of
// inline at a specific line. The reader sees the same AI-disclosure
// header and comment narrative as an inline post, plus a short italicised
// preamble that records the line number the model originally intended
// (e.g. "_Intended for line 42 — anchored to the file because that line
// isn't on a hunk in the current diff._"). Suggestion blocks are dropped:
// GitHub's one-click "Apply suggestion" UI only works on line-anchored
// comments, so including a ```suggestion block on a file-level comment
// renders as inert code and risks the reader copy-pasting it manually
// against the wrong line.
func ReviewCommentBodyForFileLevel(specialist string, f Finding) string {
	body := fmt.Sprintf(aiCommentLead, specialist)
	if f.Line > 0 {
		body += fmt.Sprintf("_Intended for line %d — anchored to the file because that line isn't on a hunk in the current diff._\n\n", f.Line)
	} else {
		body += "_Anchored to the file (no specific diff line)._\n\n"
	}
	body += f.Comment
	return body
}

// combineAuthorPrompts joins vibe-coach prompts into one paste block for the
// review body. Each prompt is rendered as "## <title>\n\n<text>" inside a
// plain `text` fence, separated from the next prompt by "---".
//
// The "## " title prefix is plain text inside the fence (markdown isn't
// rendered there), but it still gives the author and any AI assistant a
// strong visual / structural cue that each section is its own topic. This
// matters when the vibe-coach correctly returns one prompt per distinct
// topic (refactor + README + CHANGELOG = three sections) — the human
// glancing at the review needs to see at a glance that there is more than
// one piece of work to do.
func combineAuthorPrompts(prompts []AuthorPrompt) string {
	var segments []string
	for _, p := range prompts {
		text := strings.TrimSpace(p.AgentPromptText())
		if text == "" {
			continue
		}
		title := strings.TrimSpace(p.Title)
		if title != "" {
			segments = append(segments, "## "+title+"\n\n"+text)
		} else {
			segments = append(segments, text)
		}
	}
	return strings.Join(segments, "\n\n---\n\n")
}

// countNonEmptyPrompts returns the number of prompts that contribute a
// non-empty agent_prompt body to the rendered fenced block. Used by the
// renderer to size the "It contains N distinct topics" disclosure so the
// number always matches what the reader sees in the fence.
func countNonEmptyPrompts(prompts []AuthorPrompt) int {
	n := 0
	for _, p := range prompts {
		if strings.TrimSpace(p.AgentPromptText()) != "" {
			n++
		}
	}
	return n
}

// VerdictEmoji maps a canonical verdict to the emoji used in the body
// headline and the CLI summary. Empty for unknown verdicts so callers degrade
// to plain text.
func VerdictEmoji(canonical string) string {
	switch canonical {
	case VibeVerdictApprove:
		return "✅"
	case VibeVerdictRequestChanges:
		return "🔴"
	case VibeVerdictComment:
		return "💬"
	default:
		return ""
	}
}

// bodyHeadline renders the H2 title line. The verdict is folded straight into
// the headline ("## appr-ai-sal summary — 🔴 Request changes") so the author
// sees the outcome first, without a separate "Merge recommendation" section
// and duplicate "Verdict:" heading. The word "summary" (not "review") is
// deliberate — see RenderBody's framing comment.
func bodyHeadline(canonicalVerdict string) string {
	h := "## appr-ai-sal summary"
	if lbl := VibeVerdictShortLabel(canonicalVerdict); lbl != "" {
		if em := VerdictEmoji(canonicalVerdict); em != "" {
			h += " — " + em + " " + lbl
		} else {
			h += " — " + lbl
		}
	}
	return h + "\n\n"
}

// bodyCaution is the single merged AI-disclosure + human-review warning.
// It replaces the previous two stacked callouts (a disclosure blockquote plus
// a CAUTION alert) with one compact CAUTION.
//
// The `produced by **appr-ai-sal**` substring is the marker used by
// gh.DetectPriorAprrAISalActivity to recognise tool-authored bodies on
// re-runs; keep it intact when editing.
const bodyCaution = "> [!CAUTION]\n" +
	"> This summary was produced by **appr-ai-sal** (automated AI tools) to assist the human reviewer — it is **not** a replacement for manual review. Any approve, request-changes, or comment signal on this PR represents that reviewer's own judgement.\n\n"

// bodyStatsLine is the one-line orientation strip under the caution: where
// the feedback lives (inline vs PR-wide) and whether the run degraded. It
// replaces the old paragraph of prose explaining the same thing.
func bodyStatsLine(inline, prWide, degraded int) string {
	var parts []string
	if inline > 0 {
		parts = append(parts, "**"+countLabel(inline, "1 inline comment", "%d inline comments")+"** on the diff")
	}
	if prWide > 0 {
		parts = append(parts, "**"+countLabel(prWide, "1 PR-wide note", "%d PR-wide notes")+"** below")
	}
	if degraded > 0 {
		parts = append(parts, "⚠️ **"+countLabel(degraded, "1 review stage degraded", "%d review stages degraded")+"** — partial review")
	}
	if len(parts) == 0 {
		return ""
	}
	return strings.Join(parts, " · ") + "\n\n"
}

// vibeCoachSuggestedPromptsSection renders one combined fenced prompt (right
// below the headline/TL;DR area).
//
// Prompts are filtered against the draft: any prompt whose finding_refs are
// all arbiter-suppressed or user-skipped is dropped, so the rendered review
// only suggests AI prompts for findings that actually made it through to
// GitHub. Legacy / general prompts (no finding_refs) are kept unconditionally
// — those don't tie to a specific anchor.
//
// After filtering, if there are still error/critical-severity findings the
// vibe-coach didn't cover (typical failure: a PR-wide testing/docs error
// the model forgot to bundle, or a single bundled prompt that got dropped
// because its only inline ref was suppressed), synthesizeFallbackPrompts
// builds one fallback AuthorPrompt per uncovered finding so the author
// always has a paste-ready instruction for every blocker.
func vibeCoachSuggestedPromptsSection(d *Draft, vc *VibeCoachResult) string {
	if vc == nil || vc.Err != nil {
		return ""
	}
	kept, droppedTitles := filterAuthorPrompts(d, vc.Prompts)
	synthesized := synthesizeFallbackPrompts(d, kept)
	rendered := append([]AuthorPrompt(nil), kept...)
	rendered = append(rendered, synthesized...)
	if len(rendered) == 0 && len(droppedTitles) == 0 {
		return ""
	}
	combined := strings.TrimSpace(combineAuthorPrompts(rendered))
	var b strings.Builder
	if combined != "" {
		topicCount := countNonEmptyPrompts(rendered)
		b.WriteString("### 🤖 Prompt for your AI assistant\n\n")
		switch {
		case topicCount <= 1:
			b.WriteString("_Paste the fenced block below into your coding assistant (Cursor, Claude Code, etc.)._\n\n")
		default:
			fmt.Fprintf(&b, "_Paste the fenced block below into your coding assistant (Cursor, Claude Code, etc.) — **%d distinct topics** separated by `---`._\n\n", topicCount)
		}
		if len(synthesized) > 0 {
			fmt.Fprintf(&b, "_%s auto-built from blocking findings the vibe-coach didn't bundle into a paste-ready prompt; the wording is verbatim from the specialist's comment._\n\n",
				countLabel(len(synthesized), "1 topic was", "%d topics were"))
		}
		b.WriteString("```text\n")
		b.WriteString(combined)
		b.WriteString("\n```\n\n")
	}
	// Disclosure: the human reader needs to know that some follow-up
	// prompts were silently dropped because every inline finding they
	// bundled was suppressed or skipped — otherwise the verdict / summary
	// above can look mismatched ("request changes" + zero prompts). The
	// wording is deliberately scoped to "inline findings the prompt
	// pointed to" so the reader doesn't conclude that *every* finding was
	// dropped (PR-wide notes, repo-expert panel content, and general
	// findings can't be suppressed and still appear below).
	switch {
	case len(droppedTitles) == 0:
		// nothing dropped, no note.
	case combined == "":
		fmt.Fprintf(&b, "_%s dropped because the inline findings they pointed to were all suppressed by the repo arbiter or skipped during review. The verdict above is based on the broader review (PR-wide notes and repo-expert panel below, if any), not just those inline findings._\n\n",
			countLabel(len(droppedTitles), "The 1 paste-ready follow-up prompt was", "All %d paste-ready follow-up prompts were"))
	default:
		fmt.Fprintf(&b, "_%s dropped because the inline findings they pointed to were all suppressed or skipped: %s._\n\n",
			countLabel(len(droppedTitles), "1 paste-ready follow-up prompt was", "%d paste-ready follow-up prompts were"),
			joinQuoted(droppedTitles))
	}
	return b.String()
}

// countLabel returns one of two phrasings depending on whether n == 1.
// The plural template may use a single %d placeholder for the count; the
// singular template is taken verbatim.
//
// Existed because the previous "_All " + plural(n, "follow-up prompt") +
// " were dropped_" produced ungrammatical "All 1 paste-ready follow-up
// prompt were dropped" when n == 1 — singular noun, plural verb.
func countLabel(n int, singular, pluralTpl string) string {
	if n == 1 {
		return singular
	}
	if strings.Contains(pluralTpl, "%d") {
		return fmt.Sprintf(pluralTpl, n)
	}
	return pluralTpl
}

func joinQuoted(s []string) string {
	if len(s) == 0 {
		return ""
	}
	out := make([]string, len(s))
	for i, v := range s {
		out[i] = "“" + v + "”"
	}
	return strings.Join(out, ", ")
}

// RenderBody renders the top-level review body: vibe-coach verdict + summary + one
// combined AI prompt, then optional consolidated PR-wide bullets and agent failures.
// Per-specialist headings are intentionally omitted — inline-only feedback lives on the diff.
//
// The body is deliberately framed as a *summary* produced by an assistive
// tool, not as the review itself. The actual review is performed by the
// human running appr-ai-sal — any APPROVE / REQUEST_CHANGES / COMMENT
// signal on the PR represents that individual's own judgement after
// consulting the AI output. The wording here, the heading, and the
// human-reviewer disclaimer are all in service of that framing so PR
// authors don't read a green checkmark and assume "the AI approved this".
//
// The `produced by **appr-ai-sal**` substring is the marker used by
// gh.DetectPriorAprrAISalActivity to recognise tool-authored bodies on
// re-runs; it lives in bodyCaution — keep it intact when editing.
func (d *Draft) RenderBody() string {
	if d != nil && d.HasNoFindings() {
		// The standard sections (stats line, prompt, PR-wide notes) are all
		// empty when the pipeline returned nothing. Use a tailored body so the
		// GitHub APPROVE we post in this case explains why instead of looking
		// content-free.
		return bodyHeadline(VibeVerdictApprove) +
			"**No issues found by any agent** — every configured specialist reviewed this diff and produced no actionable feedback to leave on the diff or in a written summary. It recommends Approving this pull request.\n\n" +
			d.diffTruncationNote() +
			bodyCaution
	}

	// Gather process metadata and PR-wide findings up front so the headline
	// area can carry an accurate one-line stats strip.
	type agentErr struct {
		name string
		msg  string
	}
	var failures []agentErr
	var skippedStages []string
	var prWide []struct {
		specialist string
		f          Finding
	}

	for _, s := range d.Specialists {
		switch s.EffectiveOutcome() {
		case OutcomeSkipped:
			// Never ran (circuit breaker aborted the remaining stages). Listed
			// separately from failures so the reader knows the review is
			// partial rather than that the agent errored.
			skippedStages = append(skippedStages, s.Specialist)
			continue
		case OutcomeFailed:
			msg := "failed after retries"
			if s.Err != nil {
				msg = s.Err.Error()
			}
			failures = append(failures, agentErr{s.Specialist, msg})
			continue
		}
		if len(s.Findings) == 0 {
			continue
		}
		for _, f := range generalFindings(s.Findings) {
			if d.generalFindingSuppressed(s.Specialist, f) {
				continue
			}
			prWide = append(prWide, struct {
				specialist string
				f          Finding
			}{s.Specialist, f})
		}
	}

	// Demoted PR-wide findings the reviewer opted to include despite the
	// arbiter demoting them below the strictness floor. Inline demoted
	// findings post through the opt-in card flow, not here.
	var demotedIncluded []struct {
		specialist string
		f          Finding
	}
	for _, ff := range d.DemotedHidden {
		if findingIsInlinePostable(ff.Finding) {
			continue
		}
		if strings.TrimSpace(ff.Finding.Comment) == "" {
			continue
		}
		if !d.DemotedPostingEnabled(ff.Specialist, ff.Finding) {
			continue
		}
		demotedIncluded = append(demotedIncluded, struct {
			specialist string
			f          Finding
		}{ff.Specialist, ff.Finding})
	}

	vcDisp := d.effectiveVibeCoach()
	vcOK := vcDisp != nil && vcDisp.Err == nil
	verdict := ""
	if vcOK {
		verdict = NormalizeVibeVerdict(vcDisp.Verdict)
	}

	var b strings.Builder

	// 1. Headline (verdict folded in), downgrade note, TL;DR.
	b.WriteString(bodyHeadline(verdict))
	if vcOK {
		if note := strings.TrimSpace(d.VerdictReconciliationNote()); note != "" {
			b.WriteString("> " + note + "\n\n")
		}
		if s := strings.TrimSpace(vcDisp.Summary); s != "" {
			b.WriteString(s + "\n\n")
		}
	}

	// 2. Warnings and the merged AI disclosure / human-review caution.
	b.WriteString(d.diffTruncationNote())
	b.WriteString(bodyCaution)

	// 3. One-line orientation stats.
	b.WriteString(bodyStatsLine(
		len(d.FlatPostableFindingsForPost()),
		len(prWide)+len(demotedIncluded),
		len(failures)+len(skippedStages)))
	if vcOK && vcDisp.RequestChangesWithoutPrompts {
		b.WriteString("**Warning:** Verdict is **request changes**, but no paste-ready AI prompts were returned — rely on the inline comments on the diff and the PR-wide notes below (if any).\n\n")
	}

	// 4. The author's main action item: the paste-ready prompt.
	if vcOK {
		if prompts := vibeCoachSuggestedPromptsSection(d, vcDisp); prompts != "" {
			b.WriteString(prompts)
		}
	}

	// 5. Substantive findings that live in the body rather than on the diff.
	if len(prWide) > 0 {
		b.WriteString("### PR-wide notes\n\n")
		b.WriteString("_Not tied to a single changed line — all other findings are inline comments on the diff._\n\n")
		for _, item := range prWide {
			b.WriteString("- **" + string(item.f.Severity) + " · " + item.specialist + ":** " + item.f.Comment + "\n")
		}
		b.WriteString("\n")
	}
	if len(demotedIncluded) > 0 {
		b.WriteString("### PR-wide notes — included despite demotion\n\n")
		b.WriteString("_The repo arbiter demoted these below the review threshold; the reviewer chose to surface them anyway._\n\n")
		for _, item := range demotedIncluded {
			b.WriteString("- **" + item.specialist + " _(demoted by repo arbiter)_:** " + item.f.Comment + "\n")
		}
		b.WriteString("\n")
	}

	// 6. Repo expert panel: short summary + verdict adjustment stay visible,
	// rationale and suppressed-comment list collapse.
	if d.RepoArbiter != nil {
		if panel := repoExpertPanelSection(d); panel != "" {
			b.WriteString(panel)
		}
	}

	// 7. Process metadata, collapsed. The stats line above already flags a
	// degraded run; the details block carries the specifics without competing
	// with the findings for the author's attention.
	userSkips := len(d.UserSkipPostKeys)
	if len(failures)+len(skippedStages) > 0 || userSkips > 0 {
		var sum []string
		if len(failures) > 0 {
			sum = append(sum, countLabel(len(failures), "1 agent failed", "%d agents failed"))
		}
		if len(skippedStages) > 0 {
			sum = append(sum, countLabel(len(skippedStages), "1 stage skipped", "%d stages skipped"))
		}
		if userSkips > 0 {
			sum = append(sum, countLabel(userSkips, "1 suggestion skipped by reviewer", "%d suggestions skipped by reviewer"))
		}
		b.WriteString("<details>\n<summary>⚙️ Review process details — " + strings.Join(sum, " · ") + "</summary>\n\n")
		if len(failures) > 0 {
			b.WriteString("### Agent failures _(failed after retries)_\n\n")
			for _, e := range failures {
				b.WriteString("- **" + e.name + ":** _" + e.msg + "_\n")
			}
			b.WriteString("\n")
		}
		if len(skippedStages) > 0 {
			b.WriteString("### Stages skipped _(run aborted early)_\n\n")
			b.WriteString("_The run's circuit breaker stopped these agents before they ran, so this review is partial — review the areas they cover manually._\n\n")
			for _, name := range skippedStages {
				b.WriteString("- **" + name + "**\n")
			}
			b.WriteString("\n")
		}
		if userSkips > 0 {
			b.WriteString("### Reviewer choices\n\n")
			fmt.Fprintf(&b, "_%s skipped during review — not included in this GitHub post._\n\n",
				countLabel(userSkips, "1 inline suggestion", "%d inline suggestions"))
		}
		b.WriteString("</details>\n")
	}

	return b.String()
}

// diffTruncationNote renders the R3 truncation disclosure as a GitHub callout
// when the diff budgeter shaped the diff for this run, or "" otherwise. It is
// surfaced near the top of the review body so a PR author reading the summary
// knows the review did not see the full diff (which files were elided /
// truncated).
func (d *Draft) diffTruncationNote() string {
	if d == nil || d.DiffBudget == nil || !d.DiffBudget.Truncated {
		return ""
	}
	note := d.DiffBudget.DisclosureLine()
	if note == "" {
		return ""
	}
	return "> [!WARNING]\n> " + note + ". These files were not sent to the review agents; review them manually if they matter.\n\n"
}

func repoExpertPanelSection(d *Draft) string {
	ar := d.RepoArbiter
	if ar == nil {
		return ""
	}
	if ar.Err != nil {
		return "### Repo expert panel _(failed)_\n\n_" + ar.Err.Error() + "_\n\n"
	}

	// Visible part: the arbiter's plain-English summary and any verdict
	// adjustment (both substantive — the adjustment explains the headline).
	var vis strings.Builder
	if s := strings.TrimSpace(ar.UserSummary); s != "" {
		vis.WriteString(s + "\n\n")
	}
	orig := ""
	if d.VibeCoach != nil {
		orig = NormalizeVibeVerdict(d.VibeCoach.Verdict)
	}
	// Report the *reconciled* effective verdict (same value the headline and
	// posted event use), not the arbiter's raw override, so the panel never
	// claims a relaxation the override guard rejected and never disagrees with
	// the headline in the no-blockers downgrade case. When the arbiter asked
	// to relax the verdict but blocking content survived, surface that its
	// request didn't take.
	eff := NormalizeVibeVerdict(d.ReconciledMergeVerdict())
	if orig != "" && eff != "" && orig != eff {
		vis.WriteString("**Merge recommendation adjustment:** vibe-coach suggested **" + VibeVerdictShortLabel(orig) +
			"**; repo experts set effective verdict **" + VibeVerdictShortLabel(eff) + "**.\n\n")
	} else if want := NormalizeVibeVerdict(ar.VerdictOverride); want != "" && want != eff && verdictRank(want) < verdictRank(eff) {
		vis.WriteString("**Merge recommendation adjustment:** repo experts asked to relax the verdict to **" + VibeVerdictShortLabel(want) +
			"**, but blocking findings remain, so it stays **" + VibeVerdictShortLabel(eff) + "** until those are resolved or suppressed.\n\n")
	}

	// Collapsed part: rationale bullets and the suppressed-comment list are
	// reader-facing but secondary — available on click, not competing with
	// the findings.
	var det strings.Builder
	if len(ar.RationaleBullets) > 0 {
		det.WriteString("**Rationale:**\n")
		for _, r := range ar.RationaleBullets {
			r = strings.TrimSpace(r)
			if r == "" {
				continue
			}
			det.WriteString("- " + r + "\n")
		}
		det.WriteString("\n")
	}
	if len(ar.Suppressed) > 0 {
		fmt.Fprintf(&det, "**Inline comments not posted** (%d; repo arbiter):\n\n", len(ar.Suppressed))
		for _, s := range ar.Suppressed {
			fmt.Fprintf(&det, "- **%s** `%s:%d` — %s\n", s.Specialist, s.Path, s.Line, strings.TrimSpace(s.Reason))
		}
		det.WriteString("\n")
	}
	// The per-finding demotion list and the convention-witness tally are
	// intentionally NOT rendered in the posted body. A demotion only
	// re-grades a finding's severity: if the finding still clears the
	// strictness floor it already appears (at its new severity) among the
	// normal findings, and if it fell below the floor it was dropped on
	// purpose — either way a "warning → info" line the reader can't act on
	// is pure process exhaust. The convention-witness counts (N congruent /
	// divergent / unknown) are an internal QA signal that feeds the
	// arbiter, not something the PR author can do anything with. Both
	// remain on ar.Demoted / d.ConventionWitness for the TUI, tests, and any
	// future debug surfacing; the GitHub post stays limited to actionable,
	// reader-facing content.
	//
	// ar.DroppedSuppressions / DroppedDemotions are likewise omitted: they
	// leak the internal suppression-key shape ("specialist|path|line|side")
	// and add no actionable information for a human reading the review.

	if vis.Len() == 0 && det.Len() == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("### Repo expert panel\n\n")
	b.WriteString(vis.String())
	if det.Len() > 0 {
		label := "Repo-arbiter details"
		if n := len(ar.Suppressed); n > 0 {
			label += " — " + countLabel(n, "1 inline comment not posted", "%d inline comments not posted")
		}
		b.WriteString("<details>\n<summary>" + label + "</summary>\n\n")
		b.WriteString(det.String())
		b.WriteString("</details>\n\n")
	}
	return b.String()
}
