package review

import (
	"fmt"
	"strings"
)

const aiCommentLead = "**AI-generated review comment** — tool: **appr-ai-sal**, agent: **%s**\n\n"

// trimSuggestionBlock drops leading and trailing blank (whitespace-only) lines
// but preserves every content line verbatim, including its leading
// indentation. GitHub applies a ```suggestion block as the literal replacement
// for the anchored line(s), so stripping leading whitespace (as TrimSpace
// would) silently breaks indentation-sensitive files like YAML or Python: the
// reviewer clicks "Apply suggestion" and gets a left-shifted, malformed line.
func trimSuggestionBlock(s string) string {
	lines := strings.Split(s, "\n")
	start := 0
	for start < len(lines) && strings.TrimSpace(lines[start]) == "" {
		start++
	}
	end := len(lines)
	for end > start && strings.TrimSpace(lines[end-1]) == "" {
		end--
	}
	return strings.Join(lines[start:end], "\n")
}

// ReviewCommentBody formats the GitHub comment body for a finding (same as ToReview).
func ReviewCommentBody(specialist string, f Finding) string {
	body := fmt.Sprintf(aiCommentLead, specialist) + f.Comment
	if SuggestionPostsToGitHub(f) {
		if f.SuggestionSynthesized {
			body += "\n\n_Suggestion derived from the comment by appr-ai-sal — review before applying._"
		} else if f.SuggestionRepaired {
			body += "\n\n_Suggestion generated by appr-ai-sal's suggestion-repair pass — review before applying._"
		}
		s := trimSuggestionBlock(f.Suggestion)
		body += "\n\n```suggestion\n" + s + "\n```"
	}
	return body
}

// ReviewCommentBodyForFileLevel formats the GitHub comment body for a
// finding being posted at the file level (subject_type=file) instead of
// inline at a specific line. The reader sees the same AI-disclosure
// header and comment narrative as an inline post, plus a short italicised
// preamble that records the line number the model originally intended
// (e.g. "_Intended for line 42 — anchored to the file because that line
// isn't on a hunk in the current diff._"). Suggestion blocks are dropped:
// GitHub's one-click "Apply suggestion" UI only works on line-anchored
// comments, so including a ```suggestion block on a file-level comment
// renders as inert code and risks the reader copy-pasting it manually
// against the wrong line.
func ReviewCommentBodyForFileLevel(specialist string, f Finding) string {
	body := fmt.Sprintf(aiCommentLead, specialist)
	if f.Line > 0 {
		body += fmt.Sprintf("_Intended for line %d — anchored to the file because that line isn't on a hunk in the current diff._\n\n", f.Line)
	} else {
		body += "_Anchored to the file (no specific diff line)._\n\n"
	}
	body += f.Comment
	return body
}

// combineAuthorPrompts joins vibe-coach prompts into one paste block for the
// review body. Each prompt is rendered as "## <title>\n\n<text>" inside a
// plain `text` fence, separated from the next prompt by "---".
//
// The "## " title prefix is plain text inside the fence (markdown isn't
// rendered there), but it still gives the author and any AI assistant a
// strong visual / structural cue that each section is its own topic. This
// matters when the vibe-coach correctly returns one prompt per distinct
// topic (refactor + README + CHANGELOG = three sections) — the human
// glancing at the review needs to see at a glance that there is more than
// one piece of work to do.
func combineAuthorPrompts(prompts []AuthorPrompt) string {
	var segments []string
	for _, p := range prompts {
		text := strings.TrimSpace(p.AgentPromptText())
		if text == "" {
			continue
		}
		title := strings.TrimSpace(p.Title)
		if title != "" {
			segments = append(segments, "## "+title+"\n\n"+text)
		} else {
			segments = append(segments, text)
		}
	}
	return strings.Join(segments, "\n\n---\n\n")
}

// countNonEmptyPrompts returns the number of prompts that contribute a
// non-empty agent_prompt body to the rendered fenced block. Used by the
// renderer to size the "It contains N distinct topics" disclosure so the
// number always matches what the reader sees in the fence.
func countNonEmptyPrompts(prompts []AuthorPrompt) int {
	n := 0
	for _, p := range prompts {
		if strings.TrimSpace(p.AgentPromptText()) != "" {
			n++
		}
	}
	return n
}

// vibeCoachMergeSection renders the verdict + summary block. verdictNote is
// an optional one-liner shown right below the verdict heading (used when the
// reconciler downgraded the verdict because user skips removed every
// blocker — see VerdictReconciliationNote).
func vibeCoachMergeSection(vc *VibeCoachResult, verdictNote string) string {
	if vc == nil {
		return ""
	}
	v := NormalizeVibeVerdict(vc.Verdict)
	hasSummary := strings.TrimSpace(vc.Summary) != ""
	hasPrompts := len(vc.Prompts) > 0
	hasNote := strings.TrimSpace(verdictNote) != ""
	if v == "" && !hasSummary && !hasPrompts && !hasNote {
		return ""
	}
	var b strings.Builder
	b.WriteString("### Merge recommendation _(AI agent: vibe-coach)_\n\n")
	if lbl := VibeVerdictShortLabel(v); lbl != "" {
		b.WriteString("## Verdict: " + lbl + "\n\n")
	}
	if hasNote {
		b.WriteString("> " + strings.TrimSpace(verdictNote) + "\n\n")
	}
	if hasSummary {
		b.WriteString(vc.Summary)
		b.WriteString("\n\n")
	}
	if vc.RequestChangesWithoutPrompts {
		b.WriteString("**Warning:** Verdict is **request changes**, but no paste-ready AI prompts were returned. Rely on **inline comments on the diff** and PR-wide notes below (if any).\n\n")
	}
	b.WriteString("_This is guidance for reviewers; it does not submit GitHub **Approve** or **Request changes** automatically._\n\n")
	return b.String()
}

// vibeCoachSuggestedPromptsSection renders one combined fenced prompt (after merge recommendation).
//
// Prompts are filtered against the draft: any prompt whose finding_refs are
// all arbiter-suppressed or user-skipped is dropped, so the rendered review
// only suggests AI prompts for findings that actually made it through to
// GitHub. Legacy / general prompts (no finding_refs) are kept unconditionally
// — those don't tie to a specific anchor.
//
// After filtering, if there are still error/critical-severity findings the
// vibe-coach didn't cover (typical failure: a PR-wide testing/docs error
// the model forgot to bundle, or a single bundled prompt that got dropped
// because its only inline ref was suppressed), synthesizeFallbackPrompts
// builds one fallback AuthorPrompt per uncovered finding so the author
// always has a paste-ready instruction for every blocker.
func vibeCoachSuggestedPromptsSection(d *Draft, vc *VibeCoachResult) string {
	if vc == nil || vc.Err != nil {
		return ""
	}
	kept, droppedTitles := filterAuthorPrompts(d, vc.Prompts)
	synthesized := synthesizeFallbackPrompts(d, kept)
	rendered := append([]AuthorPrompt(nil), kept...)
	rendered = append(rendered, synthesized...)
	if len(rendered) == 0 && len(droppedTitles) == 0 {
		return ""
	}
	combined := strings.TrimSpace(combineAuthorPrompts(rendered))
	var b strings.Builder
	if combined != "" {
		topicCount := countNonEmptyPrompts(rendered)
		b.WriteString("### Suggested prompt for your AI assistant _(AI agent: vibe-coach)_\n\n")
		switch {
		case topicCount <= 1:
			b.WriteString("_Paste the fenced block below into your coding assistant (Cursor, Claude Code, etc.)._\n\n")
		default:
			fmt.Fprintf(&b, "_Paste the fenced block below into your coding assistant (Cursor, Claude Code, etc.). "+
				"It contains **%d distinct topics** separated by `---`; the author's AI should address each one._\n\n", topicCount)
		}
		if len(synthesized) > 0 {
			fmt.Fprintf(&b, "_%s auto-built from blocking findings the vibe-coach didn't bundle into a paste-ready prompt; the wording is verbatim from the specialist's comment._\n\n",
				countLabel(len(synthesized), "1 topic was", "%d topics were"))
		}
		b.WriteString("```text\n")
		b.WriteString(combined)
		b.WriteString("\n```\n\n")
	}
	// Disclosure: the human reader needs to know that some follow-up
	// prompts were silently dropped because every inline finding they
	// bundled was suppressed or skipped — otherwise the verdict / summary
	// above can look mismatched ("request changes" + zero prompts). The
	// wording is deliberately scoped to "inline findings the prompt
	// pointed to" so the reader doesn't conclude that *every* finding was
	// dropped (PR-wide notes, repo-expert panel content, and general
	// findings can't be suppressed and still appear below).
	switch {
	case len(droppedTitles) == 0:
		// nothing dropped, no note.
	case combined == "":
		fmt.Fprintf(&b, "_%s dropped because the inline findings they pointed to were all suppressed by the repo arbiter or skipped during review. The verdict above is based on the broader review (PR-wide notes and repo-expert panel below, if any), not just those inline findings._\n\n",
			countLabel(len(droppedTitles), "The 1 paste-ready follow-up prompt was", "All %d paste-ready follow-up prompts were"))
	default:
		fmt.Fprintf(&b, "_%s dropped because the inline findings they pointed to were all suppressed or skipped: %s._\n\n",
			countLabel(len(droppedTitles), "1 paste-ready follow-up prompt was", "%d paste-ready follow-up prompts were"),
			joinQuoted(droppedTitles))
	}
	return b.String()
}

// countLabel returns one of two phrasings depending on whether n == 1.
// The plural template may use a single %d placeholder for the count; the
// singular template is taken verbatim.
//
// Existed because the previous "_All " + plural(n, "follow-up prompt") +
// " were dropped_" produced ungrammatical "All 1 paste-ready follow-up
// prompt were dropped" when n == 1 — singular noun, plural verb.
func countLabel(n int, singular, pluralTpl string) string {
	if n == 1 {
		return singular
	}
	if strings.Contains(pluralTpl, "%d") {
		return fmt.Sprintf(pluralTpl, n)
	}
	return pluralTpl
}

func joinQuoted(s []string) string {
	if len(s) == 0 {
		return ""
	}
	out := make([]string, len(s))
	for i, v := range s {
		out[i] = "“" + v + "”"
	}
	return strings.Join(out, ", ")
}

// RenderBody renders the top-level review body: vibe-coach verdict + summary + one
// combined AI prompt, then optional consolidated PR-wide bullets and agent failures.
// Per-specialist headings are intentionally omitted — inline-only feedback lives on the diff.
//
// The body is deliberately framed as a *summary* produced by an assistive
// tool, not as the review itself. The actual review is performed by the
// human running appr-ai-sal — any APPROVE / REQUEST_CHANGES / COMMENT
// signal on the PR represents that individual's own judgement after
// consulting the AI output. The wording here, the heading, and the
// human-reviewer disclaimer are all in service of that framing so PR
// authors don't read a green checkmark and assume "the AI approved this".
//
// The `produced by **appr-ai-sal**` substring is the marker used by
// gh.DetectPriorAprrAISalActivity to recognise tool-authored bodies on
// re-runs; keep it intact when editing the disclosure below.
func (d *Draft) RenderBody() string {
	if d != nil && d.HasNoFindings() {
		// The standard disclosure mentions "inline comments on the diff" and a
		// "written summary" — both nonsensical when the pipeline returned
		// nothing. Use a tailored body so the GitHub APPROVE we post in this
		// case explains why instead of looking content-free.
		return "## appr-ai-sal summary\n\n" +
			"✅ **No issues found by any agent** — every configured specialist reviewed this diff and produced no actionable feedback to leave on the diff or in a written summary. It recommends Approving this pull request.\n\n" +
			"> [!CAUTION]\n" +
			"> The review is still manually performed by the person using appr-ai-sal. It is **not** a replacement for manual review.\n\n" +
			"> **AI disclosure:** This summary was produced by **appr-ai-sal** (automated AI tools).\n"
	}
	var b string
	b += "## appr-ai-sal summary\n\n"
	b += "> **AI disclosure:** This summary was produced by **appr-ai-sal** (automated AI tools) to assist the human reviewer. "
	b += "**Line-level feedback** appears as **inline comments on the diff** where agents cited paths and lines. "
	b += "This top-level comment summarises that feedback and offers optional paste-ready AI instructions for the author.\n\n"
	b += "> [!CAUTION]\n"
	b += "> The review is still manually performed by the person using appr-ai-sal — any approve, request-changes, or comment signal represents that individual's own review and judgement, not an automated decision. It is **not** a replacement for manual review.\n\n"

	vcDisp := d.effectiveVibeCoach()
	if vcDisp != nil && vcDisp.Err == nil {
		if merge := vibeCoachMergeSection(vcDisp, d.VerdictReconciliationNote()); merge != "" {
			b += merge
		}
		if prompts := vibeCoachSuggestedPromptsSection(d, vcDisp); prompts != "" {
			b += prompts
		}
	}
	if d.RepoArbiter != nil {
		if panel := repoExpertPanelSection(d); panel != "" {
			b += panel
		}
	}

	type agentErr struct {
		name string
		msg  string
	}
	var failures []agentErr
	var prWide []struct {
		specialist string
		f          Finding
	}

	for _, s := range d.Specialists {
		if s.Err != nil {
			failures = append(failures, agentErr{s.Specialist, s.Err.Error()})
			continue
		}
		if len(s.Findings) == 0 {
			continue
		}
		for _, f := range generalFindings(s.Findings) {
			if d.generalFindingSuppressed(s.Specialist, f) {
				continue
			}
			prWide = append(prWide, struct {
				specialist string
				f          Finding
			}{s.Specialist, f})
		}
	}

	if len(failures) > 0 {
		b += "### Agent failures\n\n"
		for _, e := range failures {
			b += "- **" + e.name + ":** _" + e.msg + "_\n"
		}
		b += "\n"
	}

	if len(prWide) > 0 {
		b += "### PR-wide notes _(no diff anchor)_\n\n"
		b += "_These could not be tied to a single changed line; every other finding from specialists is in **inline comments on the diff**._\n\n"
		for _, item := range prWide {
			b += "- **" + string(item.f.Severity) + " · " + item.specialist + ":** " + item.f.Comment + "\n"
		}
		b += "\n"
	}

	// Demoted PR-wide findings the reviewer opted to include despite the
	// arbiter demoting them below the strictness floor. Inline demoted
	// findings post through the opt-in card flow, not here.
	var demotedIncluded []struct {
		specialist string
		f          Finding
	}
	for _, ff := range d.DemotedHidden {
		if findingIsInlinePostable(ff.Finding) {
			continue
		}
		if strings.TrimSpace(ff.Finding.Comment) == "" {
			continue
		}
		if !d.DemotedPostingEnabled(ff.Specialist, ff.Finding) {
			continue
		}
		demotedIncluded = append(demotedIncluded, struct {
			specialist string
			f          Finding
		}{ff.Specialist, ff.Finding})
	}
	if len(demotedIncluded) > 0 {
		b += "### PR-wide notes — included despite demotion\n\n"
		b += "_The repo arbiter demoted these below the review threshold; the reviewer chose to surface them anyway._\n\n"
		for _, item := range demotedIncluded {
			b += "- **" + item.specialist + " _(demoted by repo arbiter)_:** " + item.f.Comment + "\n"
		}
		b += "\n"
	}

	if d != nil && len(d.UserSkipPostKeys) > 0 {
		n := len(d.UserSkipPostKeys)
		s := "s"
		if n == 1 {
			s = ""
		}
		b += "### Reviewer choices\n\n"
		b += fmt.Sprintf("_%d inline suggestion%s skipped during review — not included in this GitHub post._\n\n", n, s)
	}

	return b
}

func repoExpertPanelSection(d *Draft) string {
	ar := d.RepoArbiter
	if ar == nil {
		return ""
	}
	if ar.Err != nil {
		return "### Repo expert panel _(failed)_\n\n_" + ar.Err.Error() + "_\n\n"
	}
	var b strings.Builder
	b.WriteString("### Repo expert panel _(arbiter over per-specialist briefs)_\n\n")
	if strings.TrimSpace(ar.UserSummary) != "" {
		b.WriteString(strings.TrimSpace(ar.UserSummary))
		b.WriteString("\n\n")
	}
	if len(ar.RationaleBullets) > 0 {
		b.WriteString("**Rationale:**\n")
		for _, r := range ar.RationaleBullets {
			r = strings.TrimSpace(r)
			if r == "" {
				continue
			}
			b.WriteString("- " + r + "\n")
		}
		b.WriteString("\n")
	}
	orig := ""
	if d.VibeCoach != nil {
		orig = NormalizeVibeVerdict(d.VibeCoach.Verdict)
	}
	// Report the *reconciled* effective verdict (same value the headline and
	// posted event use), not the arbiter's raw override, so the panel never
	// claims a relaxation the override guard rejected and never disagrees with
	// the headline in the no-blockers downgrade case. When the arbiter asked
	// to relax the verdict but blocking content survived, surface that its
	// request didn't take.
	eff := NormalizeVibeVerdict(d.ReconciledMergeVerdict())
	if orig != "" && eff != "" && orig != eff {
		b.WriteString("**Merge recommendation adjustment:** vibe-coach suggested **" + VibeVerdictShortLabel(orig) +
			"**; repo experts set effective verdict **" + VibeVerdictShortLabel(eff) + "**.\n\n")
	} else if want := NormalizeVibeVerdict(ar.VerdictOverride); want != "" && want != eff && verdictRank(want) < verdictRank(eff) {
		b.WriteString("**Merge recommendation adjustment:** repo experts asked to relax the verdict to **" + VibeVerdictShortLabel(want) +
			"**, but blocking findings remain, so it stays **" + VibeVerdictShortLabel(eff) + "** until those are resolved or suppressed.\n\n")
	}
	if len(ar.Suppressed) > 0 {
		fmt.Fprintf(&b, "**Inline comments not posted** (%d; repo arbiter):\n\n", len(ar.Suppressed))
		for _, s := range ar.Suppressed {
			fmt.Fprintf(&b, "- **%s** `%s:%d` — %s\n", s.Specialist, s.Path, s.Line, strings.TrimSpace(s.Reason))
		}
		b.WriteString("\n")
	}
	// The per-finding demotion list and the convention-witness tally are
	// intentionally NOT rendered in the posted body. A demotion only
	// re-grades a finding's severity: if the finding still clears the
	// strictness floor it already appears (at its new severity) among the
	// normal findings, and if it fell below the floor it was dropped on
	// purpose — either way a "warning → info" line the reader can't act on
	// is pure process exhaust. The convention-witness counts (N congruent /
	// divergent / unknown) are an internal QA signal that feeds the
	// arbiter, not something the PR author can do anything with. Both
	// remain on ar.Demoted / d.ConventionWitness for the TUI, tests, and any
	// future debug surfacing; the GitHub post stays limited to actionable,
	// reader-facing content.
	//
	// ar.DroppedSuppressions / DroppedDemotions are likewise omitted: they
	// leak the internal suppression-key shape ("specialist|path|line|side")
	// and add no actionable information for a human reading the review.
	out := b.String()
	if out == "### Repo expert panel _(arbiter over per-specialist briefs)_\n\n" {
		return ""
	}
	return out
}
