package demo

import (
	"context"
	"fmt"
	"time"

	"github.com/madicen/appr-ai-sal/internal/aiconfig"
	"github.com/madicen/appr-ai-sal/internal/gh"
	"github.com/madicen/appr-ai-sal/internal/review"
)

// SyntheticReviewProgress emits a scripted sequence of review.Progress
// events with realistic per-stage delays so the persistent review
// overlay replays a believable run for VHS recording. Closes the
// channel with a final "done" Progress carrying a hand-built Draft so
// the approve/post flow has real cards to interact with.
//
// Stage names + Detail strings mirror the live runner exactly so the
// overlay's stage-grouping logic doesn't need a demo branch — it's the
// same Progress shape, just generated by us instead of the real
// pipeline.
func SyntheticReviewProgress(ctx context.Context, ref gh.Ref, cfg *aiconfig.Config) <-chan review.Progress {
	out := make(chan review.Progress, 16)
	go runScript(ctx, ref, cfg, out)
	return out
}

// runScript walks a deterministic timeline. Stage delays average
// ~1.5s so the resulting GIF reads at a comfortable pace; the
// specialist phase runs all five agents concurrently and finishes
// them at staggered offsets across ~10s so the overlay's stage
// chips visibly progress one-by-one. Each send/wait checks ctx.Done()
// so a hard quit (Ctrl+q) doesn't strand goroutines.
//
// Total run time: ~28s (8 pre-stages × ~1.4s + 10s specialists +
// 3 post-stages × ~1.5s).
func runScript(ctx context.Context, ref gh.Ref, cfg *aiconfig.Config, out chan<- review.Progress) {
	defer close(out)
	send := func(p review.Progress) bool {
		select {
		case <-ctx.Done():
			return false
		case out <- p:
			return true
		}
	}
	wait := func(d time.Duration) bool {
		select {
		case <-ctx.Done():
			return false
		case <-time.After(d):
			return true
		}
	}

	// Resolve the canned diff up front so the "diff" stage can report its
	// size. The final Draft is assembled by FinalReviewDraft (shared with the
	// hermetic tests) so we don't re-walk the PR fixture here.
	diff := DemoDiff(ref)

	// preStages walk the context-injection part of the pipeline —
	// each one shows a single chip transition, so ~1.5s per stage
	// gives the viewer time to read what just resolved before the
	// next chip lights up.
	const preStageDelay = 1500 * time.Millisecond

	// Stage 1: checkout (instant in demo — no real worktree).
	if !send(review.Progress{Stage: "checkout", Detail: "/tmp/appr-ai-sal-demo · review balanced"}) {
		return
	}
	if !wait(preStageDelay) {
		return
	}

	// Stage 2: diff fetched.
	if !send(review.Progress{Stage: "diff", Detail: fmt.Sprintf("%d bytes", len(diff))}) {
		return
	}
	if !wait(preStageDelay) {
		return
	}

	// Stage 3: repo-context bundle.
	if !send(review.Progress{Stage: "repo-context", Detail: "1.8 KiB"}) {
		return
	}
	if !wait(preStageDelay) {
		return
	}

	// Stage 4: repo agents (loaded from "cache" in the demo).
	if !send(review.Progress{Stage: "repo-agents", Detail: "loaded 3 brief(s)"}) {
		return
	}
	if !wait(preStageDelay) {
		return
	}

	// Stage 5: tech agents (none configured for the demo PR).
	if !send(review.Progress{Stage: "tech-agents", Detail: "none"}) {
		return
	}
	if !wait(preStageDelay) {
		return
	}

	// Stage 6: language agents.
	if !send(review.Progress{Stage: "lang-agents", Detail: "injected go"}) {
		return
	}
	if !wait(preStageDelay) {
		return
	}

	// Stage 7: per-PR repo evidence.
	if !send(review.Progress{Stage: "repo-evidence", Detail: "2.4 KiB"}) {
		return
	}
	if !wait(preStageDelay) {
		return
	}

	// Stage 8: context-vs-change summary (small AI pass).
	if !send(review.Progress{Stage: "context-summary", Detail: "412 chars"}) {
		return
	}
	if !wait(preStageDelay) {
		return
	}

	// Stage 9: specialists. The real runner can fan these out in
	// parallel, so the demo emits all five "start" events back-to-
	// back and then completes them at staggered offsets across ~10s.
	// Quick checks (formatting, design) finish first; security comes
	// last, mirroring how a real panel typically races. Each "done"
	// event paints a fresh chip transition the viewer can latch onto.
	specs := demoSpecs()
	specialistResults := make([]review.SpecialistResult, len(specs))
	// Emit every "start" event first so all five chips flip to
	// "running" simultaneously — the visual signal that this stage
	// fans out.
	for _, s := range specs {
		if !send(review.Progress{Stage: "specialist", Detail: s.name + ":start"}) {
			return
		}
	}
	// Walk the staggered finish times. Sleeping for the *delta* to
	// the next finish keeps the overall phase exactly 10s regardless
	// of how many specialists we've defined.
	phaseStart := time.Now()
	for i, s := range specs {
		nextFinish := phaseStart.Add(s.finishAt)
		if d := time.Until(nextFinish); d > 0 {
			if !wait(d) {
				return
			}
		}
		res := review.SpecialistResult{
			Specialist: s.name,
			Summary:    s.summary,
			Findings:   s.findings,
		}
		specialistResults[i] = res
		cp := res
		if !send(review.Progress{Stage: "specialist", Detail: s.name + ":done", Result: &cp}) {
			return
		}
	}

	// postStages run after specialists; each one is a single chip
	// transition so the same ~1.5s pacing applies.
	const postStageDelay = 1500 * time.Millisecond

	// Stage 10: convention witness over the testing/docs findings.
	if !send(review.Progress{Stage: "convention-witness", Detail: "start (3 findings)"}) {
		return
	}
	if !wait(postStageDelay) {
		return
	}
	if !send(review.Progress{Stage: "convention-witness", Detail: "done (3 witnesses)"}) {
		return
	}
	if !wait(500 * time.Millisecond) {
		return
	}

	// Stage 11: repo arbiter.
	if !send(review.Progress{Stage: "repo-arbiter", Detail: "start"}) {
		return
	}
	if !wait(postStageDelay) {
		return
	}
	arbiter := demoArbiterResult()
	if !send(review.Progress{Stage: "repo-arbiter", Detail: "done", Arbiter: arbiter}) {
		return
	}
	if !wait(500 * time.Millisecond) {
		return
	}

	// Stage 12: vibe-coach.
	if !send(review.Progress{Stage: "vibe-coach", Detail: "start"}) {
		return
	}
	if !wait(postStageDelay) {
		return
	}
	vibe := demoVibeResult()
	if !send(review.Progress{Stage: "vibe-coach", Detail: "done", Vibe: vibe}) {
		return
	}
	if !wait(500 * time.Millisecond) {
		return
	}

	// Stage 13: done. Build the final Draft (identical to the one
	// FinalReviewDraft returns) so the approve/post flow has cards to
	// advance through. The scripted specialistResults are the same data
	// FinalReviewDraft assembles, so reuse the shared builder to keep the
	// two paths from drifting.
	final := FinalReviewDraft(ref, cfg)
	// Canned usage/cost totals so the overlay's R1 summary line renders in
	// recordings ("14 calls · 182k in / 21k out · ~$0.43 · …").
	usage := demoRunUsage()
	_ = send(review.Progress{Stage: "done", Final: final, Usage: &usage})
}

// demoSpec is one scripted specialist result plus the offset (from the
// specialist phase start) at which SyntheticReviewProgress "finishes" it.
type demoSpec struct {
	name     string
	findings []review.Finding
	summary  string
	finishAt time.Duration
}

// demoSpecs returns the scripted specialist panel: one specialist per
// severity, each anchored to real lines in the canned diff. Shared by
// SyntheticReviewProgress (which emits them with staggered delays) and
// FinalReviewDraft (which assembles them into a completed Draft with no
// delays for hermetic tests).
func demoSpecs() []demoSpec {
	return []demoSpec{
		{review.SpecFormatting, demoFormattingFindings, "no major formatting issues; one minor wrap", 2500 * time.Millisecond},
		{review.SpecDesign, demoDesignFindings, "interface boundary noted; cohesion looks reasonable", 4500 * time.Millisecond},
		{review.SpecTesting, demoTestingFindings, "added test covers the happy path; suggest one negative case", 6500 * time.Millisecond},
		{review.SpecDocs, demoDocsFindings, "exported helper missing a usage doc", 8000 * time.Millisecond},
		{review.SpecSecurity, demoSecurityFindings, "no high-severity issues; one input-validation hardening", 10000 * time.Millisecond},
	}
}

// demoSpecialistResults builds the completed specialist results from demoSpecs.
func demoSpecialistResults() []review.SpecialistResult {
	specs := demoSpecs()
	out := make([]review.SpecialistResult, len(specs))
	for i, s := range specs {
		out[i] = review.SpecialistResult{
			Specialist: s.name,
			Summary:    s.summary,
			Findings:   s.findings,
		}
	}
	return out
}

// demoArbiterResult is the canned repo-arbiter verdict for the demo run.
func demoArbiterResult() *review.RepoArbiterResult {
	return &review.RepoArbiterResult{
		UserSummary: "Repo arbiter agrees with the specialist panel; one demote applied (testing/docs convention witness flagged a non-divergent claim).",
		RationaleBullets: []string{
			"Convention witness saw 'congruent' for the docs finding on api.md; demote one rank.",
			"Security finding stands as-is; the input-validation hardening is consistent with sibling endpoints.",
		},
		EffectiveVerdict: review.VibeVerdictRequestChanges,
	}
}

// demoVibeResult is the canned vibe-coach verdict for the demo run.
func demoVibeResult() *review.VibeCoachResult {
	return &review.VibeCoachResult{
		Verdict: review.VibeVerdictRequestChanges,
		Summary: demoVibeSummary,
	}
}

// FinalReviewDraft builds the completed demo review Draft — the exact value
// SyntheticReviewProgress emits in its terminal "done" event — without waiting
// out the scripted per-stage delays. It exists so hermetic tests (teatest
// end-to-end flows and golden-file render tests) can drive the review overlay
// against the demo fixtures instantly and deterministically. cfg may be nil
// (the strictness label is then left empty).
func FinalReviewDraft(ref gh.Ref, cfg *aiconfig.Config) *review.Draft {
	pr := LookupPR(ref)
	if pr == nil {
		fallback := DemoPullRequests()[0]
		pr = &fallback
	}
	var strictness aiconfig.ReviewStrictness
	if cfg != nil {
		strictness = cfg.ReviewStrictness
	}
	return &review.Draft{
		Ref:                        ref,
		PR:                         pr,
		Diff:                       DemoDiff(ref),
		Worktree:                   "/tmp/appr-ai-sal-demo",
		Strictness:                 strictness,
		Specialists:                demoSpecialistResults(),
		VibeCoach:                  demoVibeResult(),
		RepoArbiter:                demoArbiterResult(),
		RepositoryContext:          "demo repo-context bundle (canned)",
		ContextVersusChangeSummary: demoContextVsChange,
	}
}

// RunUsageTotals returns the canned per-run usage/cost total the demo emits,
// exported so hermetic tests can assemble a "done" progress event identical to
// SyntheticReviewProgress's terminal event.
func RunUsageTotals() review.RunUsage { return demoRunUsage() }

// demoRunUsage returns a plausible per-run usage/cost total for the scripted
// demo (14 metered calls: 5 specialists, 4 PR agents, witness, arbiter,
// vibe-coach, context-summary) so the overlay's R1 summary line reads
// realistically in VHS recordings.
func demoRunUsage() review.RunUsage {
	return review.RunUsage{
		Calls:        14,
		InputTokens:  182_000,
		OutputTokens: 21_000,
		CostUSD:      0.43,
		CostKnown:    true,
		WallClock:    6*time.Minute + 12*time.Second,
	}
}

// Demo findings: one per severity, all anchored on real lines from the
// canned diff (`internal/tui/data/commands.go`) so the line-number
// gutter renders them on real hunks. Anchor lines were chosen by
// reading demoDiffAppr742 above; if you change that diff, update these.
var (
	demoFormattingFindings = []review.Finding{
		{
			Path:     "internal/tui/data/commands.go",
			Line:     78,
			Severity: review.SeverityInfo,
			Comment:  "Consider hoisting the `demopkg.SyntheticReviewProgress` call into a small helper so the demo branch reads as a one-liner against the existing real-path code.",
		},
	}
	demoDesignFindings = []review.Finding{
		{
			Path:     "internal/tui/data/commands.go",
			Line:     78,
			Severity: review.SeverityWarning,
			Comment:  "The `demo bool` parameter on `StartReviewCmd` mixes a recording concern into the production data layer's signature. Consider an internal `data.Source` interface that real and demo paths both satisfy, so future feature flags don't keep widening this signature.",
		},
	}
	demoTestingFindings = []review.Finding{
		{
			Path:     "internal/tui/data/commands.go",
			Line:     78,
			Severity: review.SeverityInfo,
			Comment:  "No test covers the demo branch. A small unit test that asserts `StartReviewCmd(ref, cfg, true)` returns a `ReviewStartedMsg` whose channel closes within ~12s would prevent silent regressions in the recording path.",
		},
	}
	demoDocsFindings = []review.Finding{
		{
			Path:     "internal/tui/data/commands.go",
			Line:     78,
			Severity: review.SeverityWarning,
			Comment:  "Doc comment for `StartReviewCmd` doesn't mention the new `demo` parameter or its semantics. Adding a single sentence (\"when demo is true, returns a synthetic progress channel from internal/demo\") will save the next reader a hop.",
		},
	}
	demoSecurityFindings = []review.Finding{
		{
			Path:     "cmd/appr-ai-sal/main.go",
			Line:     50,
			Severity: review.SeverityError,
			Comment:  "`configureDemoEnv` calls `os.Setenv` on `APPR_AI_SAL_CONFIG_DIR` and `APPR_AI_SAL_CACHE_DIR` without restoring them on exit. If the demo binary is `exec`'d from a host process (e.g. an integration test harness) those env vars leak into the parent's children. Recommend redirecting only inside the demo process via package-level overrides instead of the global env.",
			Suggestion: `if err := os.Setenv("APPR_AI_SAL_CONFIG_DIR", cfgDir); err != nil {
    return err
}
defer os.Unsetenv("APPR_AI_SAL_CONFIG_DIR")`,
		},
	}
)

const demoVibeSummary = `Solid plumbing for the demo recording path. The synthetic progress
generator is a clean way to keep VHS reproducible without coupling the
TUI to a real AI provider, and the dry-run-by-default behaviour
prevents an accidental real post during a tape session.

Two things worth tightening before merge:

1. The ` + "`demo bool`" + ` parameter pattern is starting to multiply across
   ` + "`internal/tui/data`" + `. Now's a reasonable inflection point to introduce
   a small interface so the production path doesn't accumulate flags
   for every recording-only feature.

2. The new ` + "`configureDemoEnv`" + ` helper mutates process env vars without
   a paired restore. That's fine for the binary's lifetime, but tests
   that exec it would inherit the demo dirs. Consider a config-dir
   override that flows through Options instead.

Verdict: request changes — minor, but the env-leak in particular is
worth fixing now while the seam is fresh.
`

const demoContextVsChange = `The PR's surface area sits squarely in the runner / data plumbing seam:
no specialist prompt changes, no GitHub API surface widening, no
config-file format changes. The only public-ish surface change is
` + "`StartReviewCmd`" + `'s signature, which gains a ` + "`demo bool`" + ` flag.

The repo's existing convention is to keep the data layer thin and let
the model own UI state — this PR follows that. The synthetic progress
sequencer is well-aligned with the runner's actual stage taxonomy
(matching ` + "`Stage`" + ` strings), so the overlay's stage-grouping logic
doesn't need a demo branch.
`
